### PR TITLE
Changed crash feedback alert title; Added localizations

### PR DESCRIPTION
**Pull request by futuretap**
Added localizations for es, it, nl, pt-PT, pt;

"Previously on %@" is not understandable by most users, changed to "Crash Feedback"

### CODE REVIEW

**Comment by DerAndereAndi** [comment]
Ortwin, we believe the current title is better. Lots of people don't know what a crash is, so this does not help them. The text explains very well what happened in non tech words.

**Comment by futuretap** [comment]
The text is absolutely ok. But the title "Previosly on [appname]"? Seriously? What should that tell me?

**Comment by DerAndereAndi** [comment]
It tells you, that the alert is about something that happened previously on the app. Since you get this alert maybe 10 days after the app crashed, since you never started it again. Also non tech savvy people won't understand the wording "Crash" too, that is why the title now also says "App Name Unexpectedly Quit" with the latest pull, which is in line with Apples texts on Mac OS X.

You surely might want to keep your title in your fork. But I don't think it is a good general approach to add it in here.

The other translations are surely great and would be more than welcome.

**Comment by DerAndereAndi** [comment]
I did integrate this now, by providing the developer a choice which style of texts he wants to have. Only german and english do provide both styles, the others provide the copy of the existing localizations. For your preferences, simply set `[BWQuincyManager sharedQuincyManager].languageStyle = @"Alternate";`

**Pull request merged**
