### PR TITLE
French loc help

### PR DESCRIPTION
**Pull request by cgodefroy**
Hi, I corrected/continued the french localisation so it's more appropriate. I also added a commented out htaccess file so people know quite easily how to protect their admin directory with BasicAuth

### CODE REVIEW

**Comment by DerAndereAndi** [comment]
I cannot merge the content into the development branch. Could you please compare the content in the development branch of this repository to see if it is still required?

The .htaccess renaming is a good idea, I'll wait though to a chance to merge the complete patch.

**Comment by cgodefroy** [comment]
Hi Andreas,

sorry for the delay, I was away for Easter weekend.

I'm sorry but I don't see what you mean. Do you mean the pull request is not working, or you moved the branch too far ahead? From what I see, the latest commit of french strings is still the one from Ortwin, and his French is not the greatest ;-) .

Do you want me to for from current branch and resubmit a new pull request?

Cyril

**Comment by DerAndereAndi** [comment]
This worked now, strange. But it should not have gone into the master branch but into the develop branch. :(

**Comment by cgodefroy** [comment]
Sorry about that. I'll make sure I look at the branches more closely next time. Or can you revert and I'll clean up on my side and send you the pull request with the right branch etc?

**Comment by DerAndereAndi** [comment]
I managed to add it to develop too. I am following the git flow branching concept, so this time it was harder (I don't know why) than usually. The new auto merge button for pull requests doesn't let me change the integration branch.
Additionally the complete code is currently being fully refactored and restructured, hopefully this will be released later this week. Maybe I wasn't as cautious when merging as I should have been ;)

**Pull request merged**
