### PR TITLE
Untitled

### PR DESCRIPTION
**Pull request by ajmath**
Added bar graph that shows crashs split by platform type (3GS, 3G, 4, etc.)
- Added new attribute to crash table: platform
- Updated mac and iPhone client code to send platform along with existing xml
- Updated crash_v200.php to parse new <platform> element from incoming xml
- Updated app_versions.php, crashes.php, and groups.php to display the new graph in the place of the previously displayed details section, which is now moved into its own table directly below the graphs.

Here is an example of the updated app_versions.php now with platform type graph

### CODE REVIEW

**Comment by DerAndereAndi** [comment]
Nice one. But I'd rather move the matching of device strings to the server and let the client only submit the internal key, as it is done in https://github.com/TheRealKerni/Hockey
This way clients won't need to be updated if new devices come in. What do you think?

**Comment by ajmath** [comment]
Good point.  So maybe move the below function into common.inc and do the mapping on the receiving end of the service in crash_v200.php?

<pre><code>
protected function mapPlatform($device)
    {
        $platform = $device;
        
        switch ($device) {
            case "iPhone1,1":
                $platform = "iPhone";
                break;
            case "iPhone1,2":
                $platform = "iPhone 3G";
                break;
            case "iPhone2,1":
                $platform = "iPhone 3GS";
                break;
            case "iPhone3,1":
                $platform = "iPhone 4";
                break;
            case "iPad1,1":
                $platform = "iPad";
                break;
            case "iPod1,1":
                $platform = "iPod Touch";
                break;
            case "iPod2,1":
                $platform = "iPod Touch 2nd Gen";
                break;
            case "iPod3,1":
                $platform = "iPod Touch 3rd Gen";
                break;
            case "iPod4,1":
                $platform = "iPod Touch 4th Gen";
                break;
        }

        return $platform;
    }
    
</code></pre>


Might add some additional case statements for the mac desktop if I can round some up.

**Comment by DerAndereAndi** [comment]
I would write the device codes into the database. And translate them when displaying only.

**Comment by ajmath** [comment]
Another great point.  I've added the suggested changes to the server and changed the iPhone client to only send the hardware name (i.e. iPhone2,1).  The mac client already did this.

I started to add some cases to mapPlatform to handle the device names coming from mac desktop but the names started getting way too long to be effectively displayed in that graph.  For now they are being displayed as is.

I also shortened the names returned for iOS devices in mapPlatform to help avoid clutter on the graph display

**Comment by DerAndereAndi** [comment]
Very nice. Thanks a lot!

**Pull request merged**
